version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    environment:
      - DEBUG=1
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
     - "3000:80"
      
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend